### ISSUE TITLE
GPU not working on 0.13.0, runs on CPU

### ISSUE THREAD

**Issue by PeterTucker** [TabbyML/tabby#2551]
**Describe the bug**
TabbyML 0.13.0 doesn't seem to use my 3060 GPU. When I trigger code completion, I see the CPU run at 100%. I'm using WSL2.

docker-compose.yaml:
```
services:

  tabby:
    restart: always
    image: tabbyml/tabby:0.13.0
    command: serve --model TabbyML/DeepseekCoder-1.3B --device cuda #--chat-model Qwen2-1.5B-Instruct 
    volumes:
       - ./data:/data
    ports:
      - 8080:8080
    environment:
     - CUDA_VISIBLE_DEVICES=1
     - NVIDIA_VISIBLE_DEVICES=1
     - RUST_BACKTRACE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

On another docker container it seems to run nvidia-smi just fine:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        On  |   00000000:01:00.0  On |                  N/A |
|  0%   51C    P8             17W /  170W |     728MiB /  12288MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
nvidia-smi-test-1  |
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Information about your version**
0.13.0

**Information about your GPU**
3060

**Additional context**
Running WSL2

Task Manager when I trigger Tabby code completion:
![image](https://github.com/TabbyML/tabby/assets/1381341/4fdfaf38-c2ce-411b-8835-e1a00fa9d836)

**Comment by PeterTucker** [comment]
@wsxiaoys Anyway to fix this?

**Comment by wsxiaoys** [comment]
Please give 0.13.1-rc.0 a try to see if it fixes the issue for you.

**Comment by jtbr** [comment]
With 0.13.0 I have the same problem with docker on a linux host. I tried 0.13.1-rc.0 and it also does not use the GPU. It also does not give code completions (although the web server on port 8080 is up), although that might just be the 7B model is too big/slow.

**Comment by wsxiaoys** [comment]
Fixed in https://github.com/TabbyML/tabby/releases/tag/v0.13.1

**Comment by plohoj** [comment]
I have been experiencing the same problem on a 3060 ti, for a month. Installing extension v1.7.4 and docker v0.13.1 did not fix this problem. There is no load on the GPU, with the CPU being loaded at 100% for extended periods of time. I am using Windows WSL2 and docker-compose configuration from the GPU instructions

**Comment by PeterTucker** [comment]
Honestly, Tabby is INCREDIBLY slow on WSL/Linux. You're much better off
running the native Windows version.
